version: '3.9'

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - MOVIEBOX_API_HOST=movieboxapp.in
    networks:
      - moviebox-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "3000:80"
      - "3001:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - moviebox-network

networks:
  moviebox-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
